name: Rust

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build all Rust projects
        run: |
          for dir in */Cargo.toml; do
            project_dir=$(dirname "$dir")
            echo "Building $project_dir"
            cargo build --manifest-path "$project_dir/Cargo.toml"
          done