name: Rust

on:
  push:
    paths:
      - 'p*/**'
  pull_request:
    paths:
      - 'p*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check all projects
        run: |
          for dir in p*/Cargo.toml; do
            project_dir=$(dirname "$dir")
            echo "Checking $project_dir"
            cargo check --manifest-path "$project_dir/Cargo.toml"
          done